namespace emlak
{
    partial class Form2
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.label1 = new System.Windows.Forms.Label();
            this.label2 = new System.Windows.Forms.Label();
            this.comboBox1 = new System.Windows.Forms.ComboBox();
            this.comboBox2 = new System.Windows.Forms.ComboBox();
            this.label3 = new System.Windows.Forms.Label();
            this.label4 = new System.Windows.Forms.Label();
            this.comboBox3 = new System.Windows.Forms.ComboBox();
            this.label7 = new System.Windows.Forms.Label();
            this.label8 = new System.Windows.Forms.Label();
            this.textBox1 = new System.Windows.Forms.TextBox();
            this.textBox2 = new System.Windows.Forms.TextBox();
            this.textBox4 = new System.Windows.Forms.TextBox();
            this.textBox6 = new System.Windows.Forms.TextBox();
            this.label5 = new System.Windows.Forms.Label();
            this.label9 = new System.Windows.Forms.Label();
            this.label10 = new System.Windows.Forms.Label();
            this.label11 = new System.Windows.Forms.Label();
            this.kaydet1 = new System.Windows.Forms.Button();
            this.sil = new System.Windows.Forms.Button();
            this.grnt = new System.Windows.Forms.Button();
            this.düzelt = new System.Windows.Forms.Button();
            this.listView1 = new System.Windows.Forms.ListView();
            this.columnHeader9 = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.columnHeader10 = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.columnHeader11 = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.columnHeader12 = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.columnHeader13 = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.columnHeader14 = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.columnHeader15 = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.columnHeader16 = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.columnHeader17 = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.columnHeader1 = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.textBox7 = new System.Windows.Forms.TextBox();
            this.textBox5 = new System.Windows.Forms.TextBox();
            this.label12 = new System.Windows.Forms.Label();
            this.label6 = new System.Windows.Forms.Label();
            this.SuspendLayout();
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Location = new System.Drawing.Point(70, 30);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(141, 20);
            this.label1.TabIndex = 0;
            this.label1.Text = "gayrimenkul bilgiler";
            this.label1.Click += new System.EventHandler(this.label1_Click);
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.Location = new System.Drawing.Point(58, 129);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(82, 20);
            this.label2.TabIndex = 2;
            this.label2.Text = "şehir/semt";
            // 
            // comboBox1
            // 
            this.comboBox1.FormattingEnabled = true;
            this.comboBox1.Items.AddRange(new object[] {
            "Adana|2000 Evler",
            "Adana|Abdioğlu",
            "Adana|Akçetekir",
            "Adana|Akkapı",
            "Adana|Aslanpaşa",
            "Adana|Bahçelievler",
            "Adana|Baklalı",
            "Adana|Birkent",
            "Adana|Bozgüney",
            "Adana|Buruk",
            "Adana|Büyükmangıt",
            "Adana|Çarşı",
            "Adana|Denizli",
            "Adana|Doğankent",
            "Adana|Doruk",
            "Adana|Emek",
            "Adana|Feke",
            "Adana|Fevzipaşa",
            "Adana|Gaziköy",
            "Adana|Gazipaşa",
            "Adana|Gülbahçesi",
            "Adana|Gürselpaşa",
            "Adana|Hacıbeyli",
            "Adana|Hadırlı",
            "Adana|Hamdilli",
            "Adana|Havutlu",
            "Adana|Haydaroğlu",
            "Adana|Hükümet",
            "Adana|İmamoğlu",
            "Adana|İncirlik",
            "Adana|Kaldırım",
            "Adana|Karacaoğlan",
            "Adana|Karaısalı",
            "Adana|Karataş",
            "Adana|Karayusuflu",
            "Adana|Karsantı",
            "Adana|Karşıyaka",
            "Adana|Kazımkarabekir",
            "Adana|Keresteciler",
            "Adana|Kösreli",
            "Adana|Kurtkulağı",
            "Adana|Kurtpınar",
            "Adana|Kuruköprü",
            "Adana|Küçükdikili",
            "Adana|Kürkçüler",
            "Adana|Mahfesığmaz",
            "Adana|Mavibulvar(Yurt)",
            "Adana|Mercimek",
            "Adana|Merkez Köyler",
            "Adana|Meydan",
            "Adana|Mustafabeyli",
            "Adana|Namıkkemal",
            "Adana|Pozantı",
            "Adana|Pttevleri",
            "Adana|Remzioğuzarık",
            "Adana|Sağkaya",
            "Adana|Saimbeyli",
            "Adana|Salbaş",
            "Adana|Sanayi",
            "Adana|Sarımazı",
            "Adana|Saydam",
            "Adana|Şakirpaşa",
            "Adana|Şevkiye",
            "Adana|Tufanbeylı",
            "Adana|Türlübaş",
            "Adana|Yağcami",
            "Adana|Yakapınar",
            "Adana|Yamaçlı",
            "Adana|Yavuzlar",
            "Adana|Yeşılköy",
            "Adana|Yeşilevler",
            "Adana|Yeşiloba",
            "Adana|Yeşilyurt",
            "Adana|Yumurtalık",
            "Adana|Zeytınbelı",
            "Adana|Ziyapaşa",
            "Adıyaman|Akıncılar",
            "Adıyaman|Akpınar",
            "Adıyaman|Atakent",
            "Adıyaman|Balkar",
            "Adıyaman|Belören",
            "Adıyaman|Besni",
            "Adıyaman|Bölükyayla",
            "Adıyaman|Çakırhüyük",
            "Adıyaman|Çelikhan",
            "Adıyaman|Eskisaray",
            "Adıyaman|Gerger",
            "Adıyaman|Gölbaşı",
            "Adıyaman|Harmanlı",
            "Adıyaman|Hasancık",
            "Adıyaman|İmamağa",
            "Adıyaman|İnlice",
            "Adıyaman|Kahta",
            "Adıyaman|Kesmetepe",
            "Adıyaman|Köseceli",
            "Adıyaman|Kuyucak",
            "Adıyaman|Merkez Köyler",
            "Adıyaman|Pınarbaşı",
            "Adıyaman|Samsat",
            "Adıyaman|Sarıyaprak",
            "Adıyaman|Sincik",
            "Adıyaman|Sugözü",
            "Adıyaman|Suvarlı",
            "Adıyaman|Sümerevler",
            "Adıyaman|Şambayat",
            "Adıyaman|Tut",
            "Adıyaman|Üçgöz",
            "Adıyaman|Yarpuzlu",
            "Adıyaman|Yaylakonak",
            "Adıyaman|Yenisanayi",
            "Afyonkarahisar|Adayazı",
            "Afyonkarahisar|Ahmetpaşa",
            "Afyonkarahisar|Akharım",
            "Afyonkarahisar|Akkonak",
            "Afyonkarahisar|Akören",
            "Afyonkarahisar|Akören",
            "Afyonkarahisar|Alanyurt",
            "Afyonkarahisar|Anıtkaya",
            "Afyonkarahisar|Aşağıpiribeyli",
            "Afyonkarahisar|Atlıhisar",
            "Afyonkarahisar|Ayazini",
            "Afyonkarahisar|Bademli",
            "Afyonkarahisar|Balçıkhisar",
            "Afyonkarahisar|Ballık",
            "Afyonkarahisar|Başağaç",
            "Afyonkarahisar|Başmakçı",
            "Afyonkarahisar|Bayat",
            "Afyonkarahisar|Beyyazı",
            "Afyonkarahisar|Bolvadin",
            "Afyonkarahisar|Bozhüyük",
            "Afyonkarahisar|Büyükkalecik",
            "Afyonkarahisar|Büyükkarabağ",
            "Afyonkarahisar|Çarşı",
            "Afyonkarahisar|Çay",
            "Afyonkarahisar|Çayırbağ",
            "Afyonkarahisar|Çıkrık",
            "Afyonkarahisar|Çiçektepe",
            "Afyonkarahisar|Çobanlar",
            "Afyonkarahisar|Davulga",
            "Afyonkarahisar|Dazkırı",
            "Afyonkarahisar|Değirmenayvalı",
            "Afyonkarahisar|Dereçine",
            "Afyonkarahisar|Deresinek",
            "Afyonkarahisar|Dinar",
            "Afyonkarahisar|Dişli",
            "Afyonkarahisar|Doğanlı",
            "Afyonkarahisar|Dombayova(Uluköy)",
            "Afyonkarahisar|Döğer",
            "Afyonkarahisar|Dumlupınar",
            "Afyonkarahisar|Düzağaç",
            "Afyonkarahisar|Eber",
            "Afyonkarahisar|Efe",
            "Afyonkarahisar|Emirdağ",
            "Afyonkarahisar|Erkmen",
            "Afyonkarahisar|Evciler",
            "Afyonkarahisar|Fethibey",
            "Afyonkarahisar|Gazlıgöl",
            "Afyonkarahisar|Gebeceler",
            "Afyonkarahisar|Gökçek",
            "Afyonkarahisar|Gömü",
            "Afyonkarahisar|Güney",
            "Afyonkarahisar|Harbiş",
            "Afyonkarahisar|Haydarlı",
            "Afyonkarahisar|Hocalar",
            "Afyonkarahisar|Işıklar",
            "Afyonkarahisar|İhsaniye",
            "Afyonkarahisar|İnli",
            "Afyonkarahisar|İscehisar",
            "Afyonkarahisar|Karaadilli",
            "Afyonkarahisar|Karacaahmet",
            "Afyonkarahisar|Karacaören",
            "Afyonkarahisar|Karadirek",
            "Afyonkarahisar|Karamıkkaracaören",
            "Afyonkarahisar|Karapınar",
            "Afyonkarahisar|Kayabelen",
            "Afyonkarahisar|Kayıhan",
            "Afyonkarahisar|Kemerkaya",
            "Afyonkarahisar|Kılıçarslan",
            "Afyonkarahisar|Kırca",
            "Afyonkarahisar|Kırka",
            "Afyonkarahisar|Kızık",
            "Afyonkarahisar|Kızılören",
            "Afyonkarahisar|Kocaöz",
            "Afyonkarahisar|Koçbeyli",
            "Afyonkarahisar|Kusura",
            "Afyonkarahisar|Küçükhüyük",
            "Afyonkarahisar|Menteş",
            "Afyonkarahisar|Merkez Köyler",
            "Afyonkarahisar|Nuh",
            "Afyonkarahisar|Nuribey",
            "Afyonkarahisar|Örenkaya",
            "Afyonkarahisar|Özburun",
            "Afyonkarahisar|Pazarağaç",
            "Afyonkarahisar|Sahipata",
            "Afyonkarahisar|Salar",
            "Afyonkarahisar|Sandıklı",
            "Afyonkarahisar|Savran",
            "Afyonkarahisar|Seydiler",
            "Afyonkarahisar|Sinanpaşa",
            "Afyonkarahisar|Sorkun",
            "Afyonkarahisar|Sultandağı",
            "Afyonkarahisar|Susuz",
            "Afyonkarahisar|Sülümenli",
            "Afyonkarahisar|Sülün",
            "Afyonkarahisar|Şuhut",
            "Afyonkarahisar|Taşoluk",
            "Afyonkarahisar|Tatarlı",
            "Afyonkarahisar|Tınaztepe",
            "Afyonkarahisar|Tokuşlar",
            "Afyonkarahisar|Üçkuyu",
            "Afyonkarahisar|Yaka",
            "Afyonkarahisar|Yakasinek",
            "Afyonkarahisar|Yavaşlar",
            "Afyonkarahisar|Yaylabağı",
            "Afyonkarahisar|Yeşilçiftlik",
            "Afyonkarahisar|Yeşilhisar",
            "Afyonkarahisar|Yıprak",
            "Afyonkarahisar|Yüreğil",
            "Ağrı|Dedeli",
            "Ağrı|Diyadin",
            "Ağrı|Doğubayazıt",
            "Ağrı|Eleşkirt",
            "Ağrı|Fevziçakmak",
            "Ağrı|Hamur",
            "Ağrı|Kazımkarabekir",
            "Ağrı|Merkez Köyler",
            "Ağrı|Patnos",
            "Ağrı|Tahir",
            "Ağrı|Taşlıçay",
            "Ağrı|Tutak",
            "Ağrı|Yayladüzü",
            "Ağrı|Yücekapı",
            "Aksaray|Acıpınar",
            "Aksaray|Ağaçören",
            "Aksaray|Akçakent",
            "Aksaray|Altınkaya",
            "Aksaray|Armutlu",
            "Aksaray|Bağlıkaya",
            "Aksaray|Balcı",
            "Aksaray|Bekarlar",
            "Aksaray|Boğazköy",
            "Aksaray|Bozkır",
            "Aksaray|Camili",
            "Aksaray|Çarşı",
            "Aksaray|Çiftevi",
            "Aksaray|Demirci",
            "Aksaray|Devedamı",
            "Aksaray|Doğantarla",
            "Aksaray|Eskil",
            "Aksaray|Eşmekaya",
            "Aksaray|Gülağaç",
            "Aksaray|Gülpınar",
            "Aksaray|Güzelyurt",
            "Aksaray|Harmandalı",
            "Aksaray|Helvadere",
            "Aksaray|Ihlara",
            "Aksaray|Ilısu",
            "Aksaray|İncesu",
            "Aksaray|Karkın",
            "Aksaray|Kutlu",
            "Aksaray|Merkez Köyler",
            "Aksaray|Minarecik",
            "Aksaray|Ortaköy",
            "Aksaray|Ozancık",
            "Aksaray|Sağlık",
            "Aksaray|Saratlı",
            "Aksaray|Sarayhan",
            "Aksaray|Sarıkaraman",
            "Aksaray|Sarıyahşi",
            "Aksaray|Selime",
            "Aksaray|Sevinçli",
            "Aksaray|Sofular",
            "Aksaray|Taşpınar",
            "Aksaray|Topakkaya",
            "Aksaray|Ulukışla",
            "Aksaray|Yenıkent",
            "Aksaray|Yeşılova",
            "Amasya|5.Ana Jet Üssü",
            "Amasya|Akınoğlu(Tekke)",
            "Amasya|Alpaslan",
            "Amasya|Amasya Teknik İşler",
            "Amasya|Aydınca",
            "Amasya|Ballıdere",
            "Amasya|Belevi",
            "Amasya|Boraboy",
            "Amasya|Damlaçimen",
            "Amasya|Dereboyu",
            "Amasya|Destek",
            "Amasya|Doğantepe",
            "Amasya|Esençay",
            "Amasya|Ezinepazar",
            "Amasya|Gediksaray",
            "Amasya|General Hikmet Akıncı",
            "Amasya|Gökmedrese",
            "Amasya|Göynücek",
            "Amasya|Gümüşhacıköy",
            "Amasya|Hamamözü",
            "Amasya|Kayabaşı",
            "Amasya|Kayadüzü",
            "Amasya|Küçük Sanayi Sitesi",
            "Amasya|Merkez Köyler",
            "Amasya|Merzifon",
            "Amasya|Özbaraklı",
            "Amasya|Suluova",
            "Amasya|Taşova",
            "Amasya|Uluköy",
            "Amasya|Uygur",
            "Amasya|Yassıçal",
            "Amasya|Yeşilyenice",
            "Amasya|Ziyaret",
            "Ankara|A.O.Çiftliği(Aoç)",
            "Ankara|Abidinpaşa",
            "Ankara|Afşar",
            "Ankara|Ahlatlıbel",
            "Ankara|Akdere",
            "Ankara|Akın",
            "Ankara|Aktepe",
            "Ankara|Akyurt",
            "Ankara|Altındağ",
            "Ankara|Anafartalar",
            "Ankara|Ayaş",
            "Ankara|Aydınlıkevler",
            "Ankara|Ayrancı",
            "Ankara|Bağlum",
            "Ankara|Bahçekapı",
            "Ankara|Bahçelievler",
            "Ankara|Bala",
            "Ankara|Balçıkhisar",
            "Ankara|Balgat",
            "Ankara|Batıkent",
            "Ankara|Beypazarı",
            "Ankara|Bilkent",
            "Ankara|Boğaziçi",
            "Ankara|Bumsuz",
            "Ankara|Cebeci",
            "Ankara|Çağa",
            "Ankara|Çalış",
            "Ankara|Çalören",
            "Ankara|Çamlıdere",
            "Ankara|Çankaya",
            "Ankara|Çarşı",
            "Ankara|Çayırhan",
            "Ankara|Çayyolu",
            "Ankara|Çeltikçi",
            "Ankara|Çubuk",
            "Ankara|Demetevler",
            "Ankara|Demirlibahçe",
            "Ankara|Devekovan",
            "Ankara|Dikmen",
            "Ankara|Elmadağ",
            "Ankara|Elvankent",
            "Ankara|Eryamanevleri",
            "Ankara|Esat",
            "Ankara|Esertepe(Yayla)",
            "Ankara|Etimesgut",
            "Ankara|Etlik(İncirli)",
            "Ankara|Evren",
            "Ankara|Fatih",
            "Ankara|Gaziosmanpaşa(Gop)",
            "Ankara|Göksu",
            "Ankara|Gölbaşı",
            "Ankara|Güdül",
            "Ankara|Gülhüyük",
            "Ankara|Gülveren",
            "Ankara|Hasköy",
            "Ankara|Haymana",
            "Ankara|Hisar",
            "Ankara|Hürriyet",
            "Ankara|Hüseyingazi",
            "Ankara|İskitler",
            "Ankara|İstasyon",
            "Ankara|İvedikorganizesanayi",
            "Ankara|Kacarlı",
            "Ankara|Kalaba",
            "Ankara|Kalecik",
            "Ankara|Karaşar",
            "Ankara|Karşıyaka",
            "Ankara|Kavaklıdere",
            "Ankara|Kayaş",
            "Ankara|Kazan",
            "Ankara|Kırbaşı",
            "Ankara|Kırkonaklar",
            "Ankara|Kızılay",
            "Ankara|Kızılca",
            "Ankara|Kızılcahamam",
            "Ankara|Maltepe",
            "Ankara|Mamak",
            "Ankara|Merkez Köyler",
            "Ankara|Mevlana",
            "Ankara|Misket",
            "Ankara|Muhabereokulu",
            "Ankara|Nallıhan",
            "Ankara|Oltan",
            "Ankara|Opera/Gençlikparkı",
            "Ankara|Organizesanayi",
            "Ankara|Ostim",
            "Ankara|Otuzağustos",
            "Ankara|Önder",
            "Ankara|Öveçler",
            "Ankara|Peçenek",
            "Ankara|Plevne",
            "Ankara|Polatlı",
            "Ankara|Pursaklar",
            "Ankara|Samanpazarı",
            "Ankara|Sanatoryum",
            "Ankara|Sarayköy",
            "Ankara|Sarıyar",
            "Ankara|Selçuklu",
            "Ankara|Sıhhıye",
            "Ankara|Sincan",
            "Ankara|Siteler",
            "Ankara|Sorgun",
            "Ankara|Söğütözü",
            "Ankara|Susuz",
            "Ankara|Şehitkubilay",
            "Ankara|Şenlik(Güçlükaya)",
            "Ankara|Şentepe",
            "Ankara|Şereflikoçhisar",
            "Ankara|Şeyhşamil",
            "Ankara|Tbmm",
            "Ankara|Telsizler",
            "Ankara|Ufuktepe",
            "Ankara|Ulubatlı",
            "Ankara|Ulubey",
            "Ankara|Ulus/İsmetpaşa",
            "Ankara|Uruş",
            "Ankara|Yakacık/Yurtçu",
            "Ankara|Yenice",
            "Ankara|Yenikent",
            "Ankara|Yenimahalle",
            "Ankara|Yeşilöz",
            "Ankara|Yeşilöz",
            "Ankara|Yıldırımbeyazıt/Dışkapı",
            "Ankara|Yıldız",
            "Ankara|Yurtbeyli",
            "Ankara|Yüzüncüyılişçiblokları",
            "Ankara|Zafertepe",
            "Ankara|Zırhlıbirlikler",
            "Antalya|Ahatlı",
            "Antalya|Akçay",
            "Antalya|Akseki",
            "Antalya|Aksu",
            "Antalya|Alanya",
            "Antalya|Altınova",
            "Antalya|Arapsuyu",
            "Antalya|Bademağacı",
            "Antalya|Bademli",
            "Antalya|Bahçelievler",
            "Antalya|Belek",
            "Antalya|Belkıs",
            "Antalya|Beykonak",
            "Antalya|Beymelek",
            "Antalya|Boğazkent",
            "Antalya|Bozova",
            "Antalya|Büyükköy",
            "Antalya|Cevizli",
            "Antalya|Cikcilli",
            "Antalya|Çamyuva",
            "Antalya|Çandır",
            "Antalya|Çarşı",
            "Antalya|Çavuşköy",
            "Antalya|Çolaklı",
            "Antalya|Çomaklı",
            "Antalya|Demirtaş",
            "Antalya|Demre(Kale)",
            "Antalya|Dokuma",
            "Antalya|Döşemealtı",
            "Antalya|Duraliler",
            "Antalya|Düdenbaşı",
            "Antalya|Elmalı",
            "Antalya|Erenköy",
            "Antalya|Eskisanayi",
            "Antalya|Fener",
            "Antalya|Finike",
            "Antalya|Gazipaşa",
            "Antalya|Gebiz",
            "Antalya|Gençlik",
            "Antalya|Gömbe",
            "Antalya|Göynük",
            "Antalya|Güçlüköy",
            "Antalya|Gündoğmuş",
            "Antalya|Güzelbağ",
            "Antalya|Hasyurt",
            "Antalya|İbradı (Aydınkent)",
            "Antalya|Kadriye",
            "Antalya|Kalkan",
            "Antalya|Karadayı",
            "Antalya|Karaöz",
            "Antalya|Kaş",
            "Antalya|Kemer",
            "Antalya|Kınık",
            "Antalya|Kızılot",
            "Antalya|Kızıltoprak",
            "Antalya|Konaklı",
            "Antalya|Korkuteli",
            "Antalya|Köprülü",
            "Antalya|Kumluca",
            "Antalya|Kuyucak",
            "Antalya|Küçükköy",
            "Antalya|Lara",
            "Antalya|Liman",
            "Antalya|Manavgat",
            "Antalya|Mavikent",
            "Antalya|Meltem",
            "Antalya|Merkez Köyler",
            "Antalya|Meydankavağı",
            "Antalya|Obagöl",
            "Antalya|Ormana",
            "Antalya|Ortaköy",
            "Antalya|Payallar",
            "Antalya|Sahilkent",
            "Antalya|Senir",
            "Antalya|Serik",
            "Antalya|Side",
            "Antalya|Süleymaniye",
            "Antalya|Sütçüler",
            "Antalya|Taşağıl",
            "Antalya|Tekirova",
            "Antalya|Tosmur",
            "Antalya|Turunçova",
            "Antalya|Türkler",
            "Antalya|Varsak",
            "Antalya|Yarpuz",
            "Antalya|Yelten",
            "Antalya|Yeniemek",
            "Antalya|Yenigün",
            "Antalya|Yeşilköy",
            "Antalya|Yeşilyayla",
            "Antalya|Yeşilyurt",
            "Antalya|Yukarıkocayatak",
            "Antalya|Yuva",
            "Ardahan|Ardahan",
            "Ardahan|Aşıkşenlik",
            "Ardahan|Çıldır",
            "Ardahan|Damal",
            "Ardahan|Göle",
            "Ardahan|Hanak",
            "Ardahan|Merkez Köyler",
            "Ardahan|Posof",
            "Artvin|Ardanuç",
            "Artvin|Arhavi",
            "Artvin|Artvin",
            "Artvin|Borçka",
            "Artvin|Damar",
            "Artvin|Göktaş",
            "Artvin|Hopa",
            "Artvin|Kemalpaşa",
            "Artvin|Kılıçkaya",
            "Artvin|Merkez Köyler",
            "Artvin|Meydancık",
            "Artvin|Şavşat",
            "Artvin|Yusufeli",
            "Aydın|Acarlar",
            "Aydın|Akbük",
            "Aydın|Akçaova",
            "Aydın|Akyeniköy",
            "Aydın|Ataeymir",
            "Aydın|Atburgazı",
            "Aydın|Atça",
            "Aydın|Bağarası",
            "Aydın|Başaran",
            "Aydın|Bıyıklı",
            "Aydın|Bozdoğan",
            "Aydın|Çarşı",
            "Aydın|Çeştepe",
            "Aydın|Çine",
            "Aydın|Çubukdağı",
            "Aydın|Dalama",
            "Aydın|Davutlar",
            "Aydın|Germencik",
            "Aydın|Geyre",
            "Aydın|Güllübahçe",
            "Aydın|Güzelçamlı",
            "Aydın|Hıdırbeyli",
            "Aydın|Horsunlu",
            "Aydın|İncirliova",
            "Aydın|Karacasu",
            "Aydın|Karpuzlu",
            "Aydın|Koçarlı",
            "Aydın|Köşk",
            "Aydın|Kurtuluş",
            "Aydın|Kuşadası",
            "Aydın|Kuyucak",
            "Aydın|Merkez Köyler",
            "Aydın|Mursallı",
            "Aydın|Nazilli",
            "Aydın|Ortaklar",
            "Aydın|Ovaeymir",
            "Aydın|Pamukören",
            "Aydın|Pirlibey",
            "Aydın|Salavatlı",
            "Aydın|Sanayi",
            "Aydın|Sarıkemer",
            "Aydın|Savuca",
            "Aydın|Sazlıköy",
            "Aydın|Söke",
            "Aydın|Sultanhisar",
            "Aydın|Sümer",
            "Aydın|Tepecik",
            "Aydın|Umurlu",
            "Aydın|Yamalak",
            "Aydın|Yazıkent",
            "Aydın|Yenice",
            "Aydın|Yenidoğan",
            "Aydın|Yenihisar",
            "Aydın|Yeniköy",
            "Aydın|Yenipazar",
            "Balıkesir|Adnanmenderes",
            "Balıkesir|Akçay",
            "Balıkesir|Aksakal",
            "Balıkesir|Alibeyadası",
            "Balıkesir|Altınoluk",
            "Balıkesir|Altınova",
            "Balıkesir|Anajetüstü",
            "Balıkesir|Avşa",
            "Balıkesir|Aydıncık(Edincik)",
            "Balıkesir|Ayvalık",
            "Balıkesir|Bahçelievler",
            "Balıkesir|Bakımokulu",
            "Balıkesir|Balya",
            "Balıkesir|Bandırma",
            "Balıkesir|Bigadiç",
            "Balıkesir|Burhaniye",
            "Balıkesir|Büyükdere",
            "Balıkesir|Büyükyenice",
            "Balıkesir|Çağış",
            "Balıkesir|Dursunbey",
            "Balıkesir|Edremit",
            "Balıkesir|Erdek",
            "Balıkesir|Göbel",
            "Balıkesir|Gökçeyazı",
            "Balıkesir|Gölcük",
            "Balıkesir|Gömeç",
            "Balıkesir|Gönen",
            "Balıkesir|Gündoğan",
            "Balıkesir|Güre",
            "Balıkesir|Havran",
            "Balıkesir|Ilıca",
            "Balıkesir|İskele",
            "Balıkesir|İvrindi",
            "Balıkesir|Kadıköy",
            "Balıkesir|Karaağaç",
            "Balıkesir|Karapürçek",
            "Balıkesir|Karşıyaka",
            "Balıkesir|Kayapa",
            "Balıkesir|Kepsut",
            "Balıkesir|Kızıksa",
            "Balıkesir|Kocaavşar",
            "Balıkesir|Korucu",
            "Balıkesir|Küçükköy",
            "Balıkesir|Manyas",
            "Balıkesir|Marmara",
            "Balıkesir|Merkez Köyler",
            "Balıkesir|Narlı",
            "Balıkesir|Ocaklar",
            "Balıkesir|Pamukçu",
            "Balıkesir|Paşaalanı",
            "Balıkesir|Pelitköy",
            "Balıkesir|Sakarya",
            "Balıkesir|Salur",
            "Balıkesir|Saraylar",
            "Balıkesir|Sarıbeyler",
            "Balıkesir|Sarıköy",
            "Balıkesir|Sarımsaklı",
            "Balıkesir|Savaştepe",
            "Balıkesir|Sındırgı",
            "Balıkesir|Susurluk",
            "Balıkesir|Şamlı",
            "Balıkesir|Yağcılar",
            "Balıkesir|Yaylabayır",
            "Balıkesir|Yüreğil",
            "Balıkesir|Zeytinli",
            "Bartın|Abdipaşa",
            "Bartın|Amasra",
            "Bartın|Arıt",
            "Bartın|Demirciler",
            "Bartın|Kozcağız",
            "Bartın|Kumluca",
            "Bartın|Kurucaşile",
            "Bartın|Merkez Köyler",
            "Bartın|Ulus",
            "Bartın|Yenisanayi",
            "Batman|Balpınar",
            "Batman|Bekirhan(Uzunçayır)",
            "Batman|Beşiri",
            "Batman|Çarşı",
            "Batman|Gap",
            "Batman|Gercüş",
            "Batman|Hasankeyf",
            "Batman|Hisar",
            "Batman|İkiköprü",
            "Batman|Kayapınar",
            "Batman|Kozluk",
            "Batman|Kültür",
            "Batman|Merkez Köyler",
            "Batman|Petrol",
            "Batman|Sason",
            "Bayburt|Akşar",
            "Bayburt|Arpalı",
            "Bayburt|Aydıntepe",
            "Bayburt|Bayburt",
            "Bayburt|Beşpınar",
            "Bayburt|Çayıryolu",
            "Bayburt|Demirözü",
            "Bayburt|Gökçedere",
            "Bayburt|Konursu",
            "Bayburt|Merkez Köyler",
            "Bilecik|Bayırköy",
            "Bilecik|Bilecik",
            "Bilecik|Bozüyük",
            "Bilecik|Dodurga",
            "Bilecik|Gölpazarı",
            "Bilecik|İnhisar",
            "Bilecik|Merkez Köyler",
            "Bilecik|Osmaneli",
            "Bilecik|Pazaryeri",
            "Bilecik|Söğüt",
            "Bilecik|Vezirhan",
            "Bilecik|Yenipazar",
            "Bingöl|Adaklı",
            "Bingöl|Ağaçeli(Ilıcalar)",
            "Bingöl|Arakonak",
            "Bingöl|Bingöl",
            "Bingöl|Genç",
            "Bingöl|Karlıova",
            "Bingöl|Kiğı",
            "Bingöl|Merkez Köyler",
            "Bingöl|Sancak",
            "Bingöl|Servi",
            "Bingöl|Solhan",
            "Bingöl|Yayladere",
            "Bingöl|Yedisu",
            "Bitlis|Adilcevaz",
            "Bitlis|Ahlat",
            "Bitlis|Aydınlar",
            "Bitlis|Bitlis",
            "Bitlis|Bölükyazı",
            "Bitlis|Göldüzü",
            "Bitlis|Güroymak",
            "Bitlis|Hizan",
            "Bitlis|Merkez Köyler",
            "Bitlis|Mutki",
            "Bitlis|Ovakışla",
            "Bitlis|Tatvan",
            "Bitlis|Yelkenli",
            "Bolu|Aşağısoku/Sanayi",
            "Bolu|Dörtdivan",
            "Bolu|Gerede",
            "Bolu|Gökçesu",
            "Bolu|Göynük",
            "Bolu|İhsaniye/Gölyüzü",
            "Bolu|Karacasu",
            "Bolu|Karamanlı",
            "Bolu|Kıbrıscık",
            "Bolu|Mengen",
            "Bolu|Merkez Köyler",
            "Bolu|Mudurnu",
            "Bolu|Pazarköy",
            "Bolu|Seben",
            "Bolu|Taşkesti",
            "Bolu|Yeniçağa",
            "Burdur|Ağlasun",
            "Burdur|Altınyayla(Dirmil)",
            "Burdur|Bağsaray",
            "Burdur|Bahçelievler",
            "Burdur|Bayır",
            "Burdur|Beyköy",
            "Burdur|Bucak",
            "Burdur|Büğdüz",
            "Burdur|Çamlık",
            "Burdur|Çanaklı",
            "Burdur|Çavdır",
            "Burdur|Çeltikçi",
            "Burdur|Çeşmedamı",
            "Burdur|Gölhisar",
            "Burdur|Gündoğdu",
            "Burdur|Güney",
            "Burdur|Hasanpaşa",
            "Burdur|İbecik",
            "Burdur|Karamanlı",
            "Burdur|Kemer",
            "Burdur|Kızılkaya",
            "Burdur|Kocaaliler",
            "Burdur|Kozağaç",
            "Burdur|Kozluca",
            "Burdur|Merkez Köyler",
            "Burdur|Salda",
            "Burdur|Sanayi",
            "Burdur|Söğüt",
            "Burdur|Tefenni",
            "Burdur|Ürkütlü",
            "Burdur|Yenice",
            "Burdur|Yeşilbaşköy",
            "Burdur|Yeşilova",
            "Burdur|Yusufca",
            "Bursa|Alemdar",
            "Bursa|Altıparmak",
            "Bursa|Bahar",
            "Bursa|Barakfakih",
            "Bursa|Beşevler",
            "Bursa|Boyalıca",
            "Bursa|Büyükorhan",
            "Bursa|Cerrah",
            "Bursa|Çalı",
            "Bursa|Çarşı",
            "Bursa|Çekirge",
            "Bursa|Çeltikçi",
            "Bursa|Davutkadı",
            "Bursa|Demirtaş",
            "Bursa|Elbeyli",
            "Bursa|Emek",
            "Bursa|Ertuğrul",
            "Bursa|Esenevler",
            "Bursa|Fethiye",
            "Bursa|Geçit",
            "Bursa|Gemlik",
            "Bursa|Görükle",
            "Bursa|Göynükbelen",
            "Bursa|Gürsu",
            "Bursa|Güzelyalı",
            "Bursa|Hamitler",
            "Bursa|Harmancık",
            "Bursa|Hisar",
            "Bursa|Hüdavendigar",
            "Bursa|Hürriyet",
            "Bursa|İhsaniye",
            "Bursa|İnegöl",
            "Bursa|İznik",
            "Bursa|Kaplıkaya",
            "Bursa|Karacabey",
            "Bursa|Karıncalı",
            "Bursa|Kayapa",
            "Bursa|Kayhan",
            "Bursa|Kazımkarabekir",
            "Bursa|Keles",
            "Bursa|Kestel",
            "Bursa|Kınık",
            "Bursa|Kurşunlu",
            "Bursa|Küçükbalıklı",
            "Bursa|Küçükkumla",
            "Bursa|Kükürtlü",
            "Bursa|Küplüpınar",
            "Bursa|Maksem",
            "Bursa|Merkez Köyler",
            "Bursa|Mudanya",
            "Bursa|Muradiye",
            "Bursa|Mustafakemalpaşa",
            "Bursa|Orhaneli",
            "Bursa|Orhangazi",
            "Bursa|Ortabağlar",
            "Bursa|Ovaakça",
            "Bursa|Reyhan",
            "Bursa|Setbaşı",
            "Bursa|Şirinevler",
            "Bursa|Tahtaköprü",
            "Bursa|Tatkavaklı -Acente",
            "Bursa|Tepecik",
            "Bursa|Ulu",
            "Bursa|Umurbey",
            "Bursa|Yalıntaş -Acente",
            "Bursa|Yeniceköy",
            "Bursa|Yenişehir",
            "Bursa|Yeşilova",
            "Bursa|Yıldırım",
            "Bursa|Zafer",
            "Bursa|Zeytinbağı",
            "Çanakkale|Akçakoyun",
            "Çanakkale|Ayvacık",
            "Çanakkale|Balıklıçeşme",
            "Çanakkale|Barbaros",
            "Çanakkale|Bayramiç",
            "Çanakkale|Biga",
            "Çanakkale|Bolayır",
            "Çanakkale|Bozcaada",
            "Çanakkale|Çan",
            "Çanakkale|Çanakkale",
            "Çanakkale|Çardak",
            "Çanakkale|Eceabat",
            "Çanakkale|Erenköy",
            "Çanakkale|Evreşe",
            "Çanakkale|Ezine",
            "Çanakkale|Gelibolu",
            "Çanakkale|Geyikli",
            "Çanakkale|Gökçeada(İmroz)",
            "Çanakkale|Gümüşçay",
            "Çanakkale|Hamdibey",
            "Çanakkale|Kalkım",
            "Çanakkale|Karabiga",
            "Çanakkale|Kavakköy",
            "Çanakkale|Kepez",
            "Çanakkale|Kozçeşme",
            "Çanakkale|Kumkale",
            "Çanakkale|Küçükkuyu",
            "Çanakkale|Lapseki",
            "Çanakkale|Mahmudiye",
            "Çanakkale|Merkez Köyler",
            "Çanakkale|Pazarköy",
            "Çanakkale|Terzialan",
            "Çanakkale|Umurbey",
            "Çanakkale|Yenice",
            "Çanakkale|Yeniçiftlik",
            "Çankırı|Atkaracalar",
            "Çankırı|Bayramören",
            "Çankırı|Çardaklı",
            "Çankırı|Çarşı",
            "Çankırı|Çavundur",
            "Çankırı|Çerkeş",
            "Çankırı|Dodurga",
            "Çankırı|Dumanlı",
            "Çankırı|Eldivan",
            "Çankırı|Elmalı",
            "Çankırı|Gümerdiğin",
            "Çankırı|Gürpınar",
            "Çankırı|Hacımuslu",
            "Çankırı|Ilgaz",
            "Çankırı|İkizören",
            "Çankırı|Kalfat",
            "Çankırı|Kızılırmak",
            "Çankırı|Korgun",
            "Çankırı|Kurşunlu",
            "Çankırı|Merkez Köyler",
            "Çankırı|Orta",
            "Çankırı|Özlü",
            "Çankırı|Saçak",
            "Çankırı|Sivricek",
            "Çankırı|Şabanözü",
            "Çankırı|Taşkaracalar",
            "Çankırı|Taşmescit",
            "Çankırı|Ünür",
            "Çankırı|Yapraklı",
            "Çankırı|Yaylakent",
            "Çankırı|Yeşildumlupınar",
            "Çankırı|Yukarıöz",
            "Çankırı|Yüklü",
            "Çorum|Alaca",
            "Çorum|Alacahöyük",
            "Çorum|Alpagut",
            "Çorum|Arifegazili",
            "Çorum|Aştavul",
            "Çorum|Bayat",
            "Çorum|Boğazkale",
            "Çorum|Büyükhırka",
            "Çorum|Çamlıca",
            "Çorum|Çopraşık",
            "Çorum|Demirşeyh",
            "Çorum|Dodurga",
            "Çorum|Düvenci",
            "Çorum|Elvançelebi",
            "Çorum|Eskialibey",
            "Çorum|Evci",
            "Çorum|Evren",
            "Çorum|Gülabibey",
            "Çorum|Hacıhamza",
            "Çorum|İskilip",
            "Çorum|Kaledere",
            "Çorum|Karahacip",
            "Çorum|Karakeçili",
            "Çorum|Kargı",
            "Çorum|Kavşut",
            "Çorum|Konaklı",
            "Çorum|Kunduzlu",
            "Çorum|Laçin",
            "Çorum|Mecitözü",
            "Çorum|Merkez Köyler",
            "Çorum|Narlı",
            "Çorum|Oğuzlar",
            "Çorum|Ortaköy",
            "Çorum|Osmancık",
            "Çorum|Seydim",
            "Çorum|Sungurlu",
            "Çorum|Tuğlu",
            "Çorum|Uğurludağ",
            "Çorum|Ulukavak",
            "Çorum|Yeniyol",
            "Çorum|Yörüklü",
            "Denizli|Acıpayam",
            "Denizli|Ahmetli",
            "Denizli|Akalan",
            "Denizli|Akkent",
            "Denizli|Akköy",
            "Denizli|Alaattin",
            "Denizli|Altıntop",
            "Denizli|Anafartalar",
            "Denizli|Babadağ",
            "Denizli|Bağbaşı",
            "Denizli|Baharlar",
            "Denizli|Baklan",
            "Denizli|Bekilli",
            "Denizli|Belevi",
            "Denizli|Beyağaç",
            "Denizli|Beylerli",
            "Denizli|Boğaziçi",
            "Denizli|Bozkurt",
            "Denizli|Buldan",
            "Denizli|Cankurtaran",
            "Denizli|Çağırgan",
            "Denizli|Çal",
            "Denizli|Çameli",
            "Denizli|Çardak",
            "Denizli|Çıtak",
            "Denizli|Çivril",
            "Denizli|Dağal",
            "Denizli|Darıveren",
            "Denizli|Dedebağı",
            "Denizli|Denizler",
            "Denizli|Dodurgalar",
            "Denizli|Duacılı",
            "Denizli|Emirhisar",
            "Denizli|Eziler",
            "Denizli|Garipköy",
            "Denizli|Gemiş",
            "Denizli|Gölbaşı",
            "Denizli|Gölcük",
            "Denizli|Gölemezli",
            "Denizli|Göveçlik",
            "Denizli|Gümüşler",
            "Denizli|Gümüşsu",
            "Denizli|Güney",
            "Denizli|Gürpınar",
            "Denizli|Hacıkaplanlar",
            "Denizli|Hançalar",
            "Denizli|Honaz",
            "Denizli|Irgıllı",
            "Denizli|Irlıganlı",
            "Denizli|Işıklı",
            "Denizli|İlbade",
            "Denizli|İnceler",
            "Denizli|İsabey",
            "Denizli|Kaklık",
            "Denizli|Kale",
            "Denizli|Karaçay",
            "Denizli|Karaköy",
            "Denizli|Kelekçi",
            "Denizli|Kınıklı",
            "Denizli|Kıralan",
            "Denizli|Kızılca",
            "Denizli|Kızılcabölük",
            "Denizli|Kızılcasöğüt",
            "Denizli|Kızılyer",
            "Denizli|Kocabaş",
            "Denizli|Kumafşarı",
            "Denizli|Kutlubey",
            "Denizli|Merkez Köyler",
            "Denizli|Nikfer",
            "Denizli|Ortaköy",
            "Denizli|Özdemirci",
            "Denizli|Pınarlar",
            "Denizli|Sarayköy",
            "Denizli|Saraylar",
            "Denizli|Selcen",
            "Denizli|Serinhisar",
            "Denizli|Sığma",
            "Denizli|Sırakapılar",
            "Denizli|Solmaz",
            "Denizli|Süller",
            "Denizli|Sümer",
            "Denizli|Tavas",
            "Denizli|Tosunlar",
            "Denizli|Ulukent",
            "Denizli|Yassıhüyük",
            "Denizli|Yatağan",
            "Denizli|Yazır",
            "Denizli|Yenicekent",
            "Denizli|Yeşildere",
            "Denizli|Yeşilyuva",
            "Denizli|Yumrutaş",
            "Diyarbakır|Ağaçlı",
            "Diyarbakır|Alatosun",
            "Diyarbakır|Alipınar",
            "Diyarbakır|Ambar",
            "Diyarbakır|Balıkçılarbaşı",
            "Diyarbakır|Bayrambaşı",
            "Diyarbakır|Bismil",
            "Diyarbakır|Cumhuriyet",
            "Diyarbakır|Çermik",
            "Diyarbakır|Çınar",
            "Diyarbakır|Çüngüş",
            "Diyarbakır|Dicle",
            "Diyarbakır|Eğil",
            "Diyarbakır|Ergani",
            "Diyarbakır|Gürbüz",
            "Diyarbakır|Hani",
            "Diyarbakır|Hazro",
            "Diyarbakır|Kayacık(Savat)",
            "Diyarbakır|Kayapınar",
            "Diyarbakır|Kaygısız",
            "Diyarbakır|Kıtılbır",
            "Diyarbakır|Kilvan(Ovabağ)",
            "Diyarbakır|Kocaköy",
            "Diyarbakır|Körhat",
            "Diyarbakır|Kulp",
            "Diyarbakır|Kuyular",
            "Diyarbakır|Lice",
            "Diyarbakır|Merkez Köyler",
            "Diyarbakır|Özekli",
            "Diyarbakır|Selahattineyyubi",
            "Diyarbakır|Silvan",
            "Diyarbakır|Suriçi",
            "Diyarbakır|Şehitlik",
            "Diyarbakır|Şölen",
            "Diyarbakır|Tepe",
            "Diyarbakır|Yenişehir",
            "Diyarbakır|Yukarısalat",
            "Diyarbakır|Yukarışeyhler",
            "Düzce|Akçakoca",
            "Düzce|Aziziye(Günlü)",
            "Düzce|Azmimilli/Çay",
            "Düzce|Beyciler",
            "Düzce|Beyköy",
            "Düzce|Boğaziçi",
            "Düzce|Cumayeri",
            "Düzce|Çilimli",
            "Düzce|Gölyaka",
            "Düzce|Gümüşova",
            "Düzce|Kalıcıkonutlar",
            "Düzce|Kaynaşlı",
            "Düzce|Konuralp",
            "Düzce|Merkez Köyler",
            "Düzce|Uğurlu Şubesi",
            "Düzce|Yığılca",
            "Edirne|Aşçıoğlu",
            "Edirne|Balıkpazarı",
            "Edirne|Beğendik",
            "Edirne|Çamlıca",
            "Edirne|Enez",
            "Edirne|Esetçe",
            "Edirne|Hacı",
            "Edirne|Havsa",
            "Edirne|İbriktepe",
            "Edirne|İpsala",
            "Edirne|Kalebayırı",
            "Edirne|Kapıkule",
            "Edirne|Kırcasalih",
            "Edirne|Kocahıdır",
            "Edirne|Kurtbey",
            "Edirne|Küplü",
            "Edirne|Lalapaşa",
            "Edirne|Londraasfaltı",
            "Edirne|Mecidiye",
            "Edirne|Meriç",
            "Edirne|Merkez Köyler",
            "Edirne|Paşayiğit",
            "Edirne|Subaşı",
            "Edirne|Sultan",
            "Edirne|Süloğlu",
            "Edirne|Şehsuvarbey",
            "Edirne|Üniversite",
            "Edirne|Yenicami",
            "Edirne|Yenikarpuzlu",
            "Edirne|Yenimuhacir",
            "Elazığ|Abdullahpaşa",
            "Elazığ|Ağın",
            "Elazığ|Akçakiraz",
            "Elazığ|Aksaray",
            "Elazığ|Alacakaya",
            "Elazığ|Arıcak",
            "Elazığ|Baltaşı",
            "Elazığ|Baskil",
            "Elazığ|Beyhanı",
            "Elazığ|Bükardı",
            "Elazığ|Çakırkaş",
            "Elazığ|Doğukent",
            "Elazığ|Erimli",
            "Elazığ|Gezin",
            "Elazığ|Hankendi",
            "Elazığ|İçme",
            "Elazığ|İzzetpaşa",
            "Elazığ|Karakoçan",
            "Elazığ|Keban",
            "Elazığ|Kovancılar",
            "Elazığ|Maden",
            "Elazığ|Merkez Köyler",
            "Elazığ|Mollakendi",
            "Elazığ|Mustafapaşa",
            "Elazığ|Nailbey",
            "Elazığ|Palu",
            "Elazığ|Sarıcan",
            "Elazığ|Sivrice",
            "Elazığ|Sürsürü",
            "Elazığ|Üçocak",
            "Elazığ|Yarımca",
            "Elazığ|Yazıkonak",
            "Elazığ|Yurtbaşı",
            "Erzincan|59.Topçutugayı",
            "Erzincan|Akşemsettin",
            "Erzincan|Akyazı",
            "Erzincan|Altınbaşak",
            "Erzincan|Bahçelievler",
            "Erzincan|Bahçeliköy",
            "Erzincan|Başbağlar",
            "Erzincan|Başpınar",
            "Erzincan|Bayırbağ",
            "Erzincan|Çadırkaya",
            "Erzincan|Çadırtepe Köyü",
            "Erzincan|Çağlayan",
            "Erzincan|Çarşı",
            "Erzincan|Çayırlı",
            "Erzincan|Çukurkuyu",
            "Erzincan|Demirkent",
            "Erzincan|Dörtler",
            "Erzincan|Dutluca",
            "Erzincan|Dutluca Merkezi",
            "Erzincan|Geçit",
            "Erzincan|Halitpaşa",
            "Erzincan|Ilıç",
            "Erzincan|İnönü",
            "Erzincan|İzzetpaşa",
            "Erzincan|Karakaya",
            "Erzincan|Kavakyolu",
            "Erzincan|Kemah",
            "Erzincan|Kemaliye",
            "Erzincan|Mercan",
            "Erzincan|Merkez Köyler",
            "Erzincan|Mollaköy",
            "Erzincan|Otlukbeli",
            "Erzincan|Refahiye",
            "Erzincan|Tercan",
            "Erzincan|Ulalar",
            "Erzincan|Uluköy",
            "Erzincan|Üzümlü",
            "Erzincan|Yalnızbağ",
            "Erzincan|Yaylabaşı",
            "Erzincan|Yoğurtlu",
            "Erzurum|Akşar",
            "Erzurum|Alvar",
            "Erzurum|Aşkale",
            "Erzurum|Aziziye/Ilıca",
            "Erzurum|Bağbaşı",
            "Erzurum|Cedit",
            "Erzurum|Çamlıkaya",
            "Erzurum|Çat",
            "Erzurum|Halilçavuş",
            "Erzurum|Hınıs",
            "Erzurum|Horasan",
            "Erzurum|İspir",
            "Erzurum|Kadana",
            "Erzurum|Kandilli",
            "Erzurum|Karaçoban",
            "Erzurum|Karayazı",
            "Erzurum|Kopal",
            "Erzurum|Köprüköy",
            "Erzurum|Köyler",
            "Erzurum|Lalapaşa",
            "Erzurum|Madenköprübaşı",
            "Erzurum|Merkez Köyler",
            "Erzurum|Mumcu",
            "Erzurum|Narman",
            "Erzurum|Oltu",
            "Erzurum|Olur",
            "Erzurum|Palandöken",
            "Erzurum|Pasinler",
            "Erzurum|Paşalı",
            "Erzurum|Pazaryolu",
            "Erzurum|Pehlivanlı",
            "Erzurum|Serdarlı",
            "Erzurum|Şekerli",
            "Erzurum|Şenkaya",
            "Erzurum|Şenyurt(Uncular)",
            "Erzurum|Tekman",
            "Erzurum|Terminal/Dadaşköy",
            "Erzurum|Tortum",
            "Erzurum|Uzundere",
            "Erzurum|Üniversite",
            "Erzurum|Yağan",
            "Erzurum|Yavi",
            "Erzurum|Yıldızkent",
            "Eskişehir|71 Evler",
            "Eskişehir|75. Yıl",
            "Eskişehir|Ağapınar",
            "Eskişehir|Akarbaşı",
            "Eskişehir|Akcami",
            "Eskişehir|Alınca",
            "Eskişehir|Alpagut",
            "Eskişehir|Alpu",
            "Eskişehir|Arifiye",
            "Eskişehir|Bahçelievler",
            "Eskişehir|Beylikova",
            "Eskişehir|Bozan",
            "Eskişehir|Büyükdere",
            "Eskişehir|Cumhuriyet",
            "Eskişehir|Çamlıca",
            "Eskişehir|Çankaya",
            "Eskişehir|Çifteler",
            "Eskişehir|Dinek",
            "Eskişehir|Doğançayır",
            "Eskişehir|Dümrek",
            "Eskişehir|Erenköy",
            "Eskişehir|Fatih",
            "Eskişehir|Fevziçakmak",
            "Eskişehir|Gökmeydan",
            "Eskişehir|Gümüşkonak",
            "Eskişehir|Gündüzler",
            "Eskişehir|Günyüzü",
            "Eskişehir|Hacıalibey",
            "Eskişehir|Han",
            "Eskişehir|İnönü",
            "Eskişehir|Kayakent",
            "Eskişehir|Kaymaz",
            "Eskişehir|Kırka",
            "Eskişehir|Kurtuluş",
            "Eskişehir|Laçin",
            "Eskişehir|Mahmudiye",
            "Eskişehir|Merkez Köyler",
            "Eskişehir|Mihalgazi",
            "Eskişehir|Mihalıçcık",
            "Eskişehir|Nasrettinhoca",
            "Eskişehir|Organizesanayibölgesi",
            "Eskişehir|Orhangazi",
            "Eskişehir|Osmangazi",
            "Eskişehir|Osmaniye",
            "Eskişehir|Sarıcakaya",
            "Eskişehir|Sazova",
            "Eskişehir|Seyitgazi",
            "Eskişehir|Sivrihisar",
            "Eskişehir|Sütlüce",
            "Eskişehir|Şirintepe",
            "Eskişehir|Uluönder",
            "Eskişehir|Yunusemre",
            "Gaziantep|Alleben",
            "Gaziantep|Altınüzüm",
            "Gaziantep|Araban",
            "Gaziantep|Arıl",
            "Gaziantep|Atatürk",
            "Gaziantep|Bağlarbaşı",
            "Gaziantep|Başpınarorganizesanayi",
            "Gaziantep|Beylerbeyi",
            "Gaziantep|Boğaziçi",
            "Gaziantep|Burç",
            "Gaziantep|Cevizli",
            "Gaziantep|Çıksorut",
            "Gaziantep|Düztepe",
            "Gaziantep|Elifköy",
            "Gaziantep|Fevzipaşa",
            "Gaziantep|Gazikent",
            "Gaziantep|Geneyik",
            "Gaziantep|Hoşgör",
            "Gaziantep|İslahiye",
            "Gaziantep|Karataş",
            "Gaziantep|Karkamış",
            "Gaziantep|Karşıyaka",
            "Gaziantep|Kavaklık",
            "Gaziantep|Konak",
            "Gaziantep|Küsget",
            "Gaziantep|Merkez Köyler",
            "Gaziantep|Merve",
            "Gaziantep|Nizip",
            "Gaziantep|Nurdağı",
            "Gaziantep|Oğuzeli",
            "Gaziantep|Perilikaya",
            "Gaziantep|Safaşehir",
            "Gaziantep|Sakçagözü",
            "Gaziantep|Sarıbaşak",
            "Gaziantep|Şahinbey",
            "Gaziantep|Şatırhüyük",
            "Gaziantep|Tabakhane",
            "Gaziantep|Yavuzeli",
            "Gaziantep|Yeşildere",
            "Gaziantep|Yeşilyurt",
            "Giresun|Aksu",
            "Giresun|Alucra",
            "Giresun|Aydındere",
            "Giresun|Aydınlar",
            "Giresun|Batlama",
            "Giresun|Bozat",
            "Giresun|Bulancak",
            "Giresun|Çaldağ",
            "Giresun|Çamoluk",
            "Giresun|Çanakçı",
            "Giresun|Çavuşlu",
            "Giresun|Dereli",
            "Giresun|Doğankent",
            "Giresun|Duroğlu",
            "Giresun|Eren Mahallesı",
            "Giresun|Espiye",
            "Giresun|Eynesil",
            "Giresun|Görele",
            "Giresun|Güce",
            "Giresun|İnişdibi",
            "Giresun|Karabörk",
            "Giresun|Karabulduk",
            "Giresun|Keşap",
            "Giresun|Kırıklı",
            "Giresun|Kovanlık",
            "Giresun|Köprübaşı",
            "Giresun|Merkez Köyler",
            "Giresun|Ören",
            "Giresun|Soğukpınar",
            "Giresun|Şebinkarahisar",
            "Giresun|Tirebolu",
            "Giresun|Tüm Köyler",
            "Giresun|Üçtepe",
            "Giresun|Yağlıdere",
            "Giresun|Yavuzkemal",
            "Giresun|Yenice",
            "Gümüşhane|Altınpınar",
            "Gümüşhane|Arzular",
            "Gümüşhane|Çayra",
            "Gümüşhane|Deredolu",
            "Gümüşhane|Gümüşgöze",
            "Gümüşhane|Gümüşhane",
            "Gümüşhane|Kale",
            "Gümüşhane|Kaş",
            "Gümüşhane|Kelkit",
            "Gümüşhane|Köse",
            "Gümüşhane|Kürtün",
            "Gümüşhane|Merkez Köyler",
            "Gümüşhane|Öbektaş",
            "Gümüşhane|Özkürtün",
            "Gümüşhane|Salyazı",
            "Gümüşhane|Söğütlü",
            "Gümüşhane|Şiran",
            "Gümüşhane|Tekke",
            "Gümüşhane|Torul",
            "Gümüşhane|Ünlüpınar",
            "Gümüşhane|Yeşilbük",
            "Hakkari|Büyükçiftlik",
            "Hakkari|Çukurca",
            "Hakkari|Derecik",
            "Hakkari|Durankaya",
            "Hakkari|Esendere",
            "Hakkari|Hakkari",
            "Hakkari|Merkez Köyler",
            "Hakkari|Şemdinli",
            "Hakkari|Yüksekova",
            "Hatay|Akbez",
            "Hatay|Akçalı",
            "Hatay|Aknehir",
            "Hatay|Aktepe",
            "Hatay|Altınçağ",
            "Hatay|Altınkaya",
            "Hatay|Altınözü",
            "Hatay|Ardıçlı",
            "Hatay|Avsuyu",
            "Hatay|Azganlık",
            "Hatay|Bekbele",
            "Hatay|Belen",
            "Hatay|Cumhuriyet",
            "Hatay|Değirmenbaşı",
            "Hatay|Denizciler",
            "Hatay|Dörtyol",
            "Hatay|Dursunlu",
            "Hatay|Ekinci",
            "Hatay|Erzin",
            "Hatay|Esentepe",
            "Hatay|Gökmeydan",
            "Hatay|Gözcüler",
            "Hatay|Gümüşgöze",
            "Hatay|Güzelburç",
            "Hatay|Hacıpaşa",
            "Hatay|Haraparası",
            "Hatay|Harbiye",
            "Hatay|Hassa",
            "Hatay|Hıdırbey(Çekmece)",
            "Hatay|Kanatlı",
            "Hatay|Karaağaç",
            "Hatay|Karaali",
            "Hatay|Karaçay",
            "Hatay|Karakese",
            "Hatay|Karaköse",
            "Hatay|Karayılan",
            "Hatay|Karlısu",
            "Hatay|Kırıkhan",
            "Hatay|Kışlak",
            "Hatay|Kışlasaray",
            "Hatay|Koyunoğlu",
            "Hatay|Kumlu",
            "Hatay|Kurtlusoğuksu",
            "Hatay|Kuşalanı",
            "Hatay|Kuzeytepe",
            "Hatay|Kuzuculu",
            "Hatay|Küçükdalyan",
            "Hatay|Küreci",
            "Hatay|Mağaracık",
            "Hatay|Merkez Köyler",
            "Hatay|Meydan",
            "Hatay|Mızraklı",
            "Hatay|Nardüzü",
            "Hatay|Narlıca",
            "Hatay|Odabaşı",
            "Hatay|Ovakent",
            "Hatay|Reyhanlı",
            "Hatay|Samandağ",
            "Hatay|Sanayi",
            "Hatay|Sarıseki",
            "Hatay|Serinyol",
            "Hatay|Söğüt",
            "Hatay|Subaşı",
            "Hatay|Sutaşı",
            "Hatay|Şenköy",
            "Hatay|Tavla",
            "Hatay|Tekebaşı",
            "Hatay|Tepeler",
            "Hatay|Tomruksuyu",
            "Hatay|Toygarlı",
            "Hatay|Turunçlu",
            "Hatay|Uluçınar(Arsuz)",
            "Hatay|Uzunbağ",
            "Hatay|Üçgüllük",
            "Hatay|Yakacık(Payas)",
            "Hatay|Yayladağı",
            "Hatay|Yaylıca",
            "Hatay|Yeditepe",
            "Hatay|Yeniyurt",
            "Hatay|Yeşilköy",
            "Hatay|Yeşilpınar",
            "Hatay|Yiğityolu(Karbeyaz)",
            "Iğdır|Aralık",
            "Iğdır|Halfeli",
            "Iğdır|Hoşhaber",
            "Iğdır|Iğdır",
            "Iğdır|Karakoyunlu",
            "Iğdır|Melekli",
            "Iğdır|Merkez Köyler",
            "Iğdır|Merkez Köyler",
            "Iğdır|Merkez Köyler",
            "Iğdır|Merkez Köyler",
            "Iğdır|Taşburun",
            "Iğdır|Tuzluca",
            "Isparta|Aksu",
            "Isparta|Anadolu",
            "Isparta|Atabey",
            "Isparta|Aydoğmuş",
            "Isparta|Ayvalıpınar",
            "Isparta|Bağıllı",
            "Isparta|Bağkonak",
            "Isparta|Barla",
            "Isparta|Büyükgökçeli",
            "Isparta|Büyükkabaca",
            "Isparta|Çarıksaraylar",
            "Isparta|Çarşı",
            "Isparta|Çelebiler",
            "Isparta|Çetince",
            "Isparta|Çiçekpınar",
            "Isparta|Dedeçam",
            "Isparta|Eğirdir",
            "Isparta|Gelendost",
            "Isparta|Gökçehöyük",
            "Isparta|Göksöğüt",
            "Isparta|Güneykent",
            "Isparta|Hüyüklü",
            "Isparta|İncesu",
            "Isparta|İslamköy",
            "Isparta|Kasımlar",
            "Isparta|Keçiborlu",
            "Isparta|Kepeci",
            "Isparta|Kesme",
            "Isparta|Kılıç",
            "Isparta|Kozluçay",
            "Isparta|Körküler",
            "Isparta|Kuleönü",
            "Isparta|Kumdanlı",
            "Isparta|Kutlubey",
            "Isparta|Kuyucak",
            "Isparta|Merkez Köyler",
            "Isparta|Özbayat",
            "Isparta|Özgüney",
            "Isparta|Pazarköy",
            "Isparta|Sarıidris",
            "Isparta|Savköy",
            "Isparta|Senir",
            "Isparta|Senirkent",
            "Isparta|Sücüllü",
            "Isparta|Sütçüler",
            "Isparta|Şarkikaraağaç",
            "Isparta|Tokmacık",
            "Isparta|Uluborlu",
            "Isparta|Uluğbey",
            "Isparta|Yakaafşar",
            "Isparta|Yalvaç",
            "Isparta|Yassıören",
            "Isparta|Yenişarbademli",
            "Isparta|Yukarıkaşıkara",
            "İstanbul|19 Mayıs",
            "İstanbul|Abbasağa",
            "İstanbul|Acıbadem",
            "İstanbul|Ağva",
            "İstanbul|Akatlar",
            "İstanbul|Akfırat",
            "İstanbul|Akıncılar",
            "İstanbul|Aksaray",
            "İstanbul|Alemdağ",
            "İstanbul|Alibeyköy",
            "İstanbul|Altınşehir",
            "İstanbul|Altıntepsi",
            "İstanbul|Altunizade",
            "İstanbul|Ambarlı",
            "İstanbul|Anadoluhisarı",
            "İstanbul|Arapcami",
            "İstanbul|Ardıçlıevler",
            "İstanbul|Arnavutköy",
            "İstanbul|Aşağıdudullu",
            "İstanbul|Atakent",
            "İstanbul|Ataköy",
            "İstanbul|Atalar",
            "İstanbul|Atatürk",
            "İstanbul|Atışalanı",
            "İstanbul|Avcılar",
            "İstanbul|Ayazağa",
            "İstanbul|Aydınevler",
            "İstanbul|Aydınlı",
            "İstanbul|Bağcılar",
            "İstanbul|Bahçeköy",
            "İstanbul|Bahçelievler",
            "İstanbul|Bahçeşehir",
            "İstanbul|Barbaros",
            "İstanbul|Başakşehir",
            "İstanbul|Bebek",
            "İstanbul|Beyazıt",
            "İstanbul|Beykoz",
            "İstanbul|Beylerbeyi",
            "İstanbul|Binkılıç",
            "İstanbul|Boğazköy",
            "İstanbul|Bolluca",
            "İstanbul|Bostancı",
            "İstanbul|Bozkurt",
            "İstanbul|Bulgurlu",
            "İstanbul|Burgazada",
            "İstanbul|Büyükada",
            "İstanbul|Büyükbakkalköy",
            "İstanbul|Büyükçekmece",
            "İstanbul|Büyükdere",
            "İstanbul|Caddebostan",
            "İstanbul|Caferağa",
            "İstanbul|Cebeci",
            "İstanbul|Celaliye(Kamiloba)",
            "İstanbul|Cevizli",
            "İstanbul|Cevizlik",
            "İstanbul|Cihangir",
            "İstanbul|Cumhuriyet",
            "İstanbul|Çağlayan",
            "İstanbul|Çakmak",
            "İstanbul|Çamçeşme",
            "İstanbul|Çanta",
            "İstanbul|Çarşı",
            "İstanbul|Çatalca",
            "İstanbul|Çavuşbaşı",
            "İstanbul|Çekmeköy",
            "İstanbul|Çeliktepe",
            "İstanbul|Çengelköy",
            "İstanbul|Çırçır",
            "İstanbul|Çırpıcı",
            "İstanbul|Çiftlikköy",
            "İstanbul|Çobançeşme",
            "İstanbul|Çubuklu",
            "İstanbul|Demirkapı",
            "İstanbul|Dolayoba",
            "İstanbul|Duatepe",
            "İstanbul|Eğitim",
            "İstanbul|Eminönü",
            "İstanbul|Emirgan",
            "İstanbul|Erenköy",
            "İstanbul|Esenler",
            "İstanbul|Esenşehir",
            "İstanbul|Esentepe",
            "İstanbul|Esenyalı",
            "İstanbul|Esenyurt",
            "İstanbul|Etiler",
            "İstanbul|Eyüp",
            "İstanbul|Eyüpsultan",
            "İstanbul|Fener",
            "İstanbul|Fenerbahçe",
            "İstanbul|Feneryolu",
            "İstanbul|Ferah",
            "İstanbul|Ferhatpaşa",
            "İstanbul|Feriköy",
            "İstanbul|Fevziçakmak",
            "İstanbul|Feyzullah",
            "İstanbul|Fikirtepe",
            "İstanbul|Firuzköy",
            "İstanbul|Florya",
            "İstanbul|Gayrettepe",
            "İstanbul|Gaziosmanpaşa",
            "İstanbul|Göksu",
            "İstanbul|Göktürk",
            "İstanbul|Göztepe",
            "İstanbul|Gülsuyu",
            "İstanbul|Gültepe",
            "İstanbul|Gümüşpala",
            "İstanbul|Güneşli",
            "İstanbul|Güngören",
            "İstanbul|Gürpınar",
            "İstanbul|Gürsel",
            "İstanbul|Halaskargazi",
            "İstanbul|Halıcıoğlu",
            "İstanbul|Halideedip",
            "İstanbul|Halkalı",
            "İstanbul|Hamidiye",
            "İstanbul|Haraççı",
            "İstanbul|Haramidere",
            "İstanbul|Harbiye",
            "İstanbul|Haseki",
            "İstanbul|Heybeliada",
            "İstanbul|Hürriyet",
            "İstanbul|Hürriyet",
            "İstanbul|Ihlamurkuyu",
            "İstanbul|İçerenköy",
            "İstanbul|İçmeler",
            "İstanbul|İdealtepe",
            "İstanbul|İkitelli",
            "İstanbul|İncirtepe",
            "İstanbul|İnkılap",
            "İstanbul|İstasyon",
            "İstanbul|İstiklal",
            "İstanbul|İstinye",
            "İstanbul|Kağıthane",
            "İstanbul|Kandilli",
            "İstanbul|Karabayır",
            "İstanbul|Karacaköy",
            "İstanbul|Karagümrük",
            "İstanbul|Kartal",
            "İstanbul|Kartaltepe",
            "İstanbul|Kasımpaşa",
            "İstanbul|Kavaklı",
            "İstanbul|Kayışdağı",
            "İstanbul|Kazımkarabekir",
            "İstanbul|Kemalpaşa",
            "İstanbul|Kemankeş",
            "İstanbul|Kınalıada",
            "İstanbul|Kıraç",
            "İstanbul|Kirazlı",
            "İstanbul|Kirazlıtepe",
            "İstanbul|Kocamustafapaşa",
            "İstanbul|Kocasinan",
            "İstanbul|Koşuyolu",
            "İstanbul|Kozyatağı",
            "İstanbul|Kumburgaz",
            "İstanbul|Kumkapı",
            "İstanbul|Kuzguncuk",
            "İstanbul|Küçükbakkalköy",
            "İstanbul|Küçükçekmece",
            "İstanbul|Küçükköy",
            "İstanbul|Küçükyalı",
            "İstanbul|Levazım",
            "İstanbul|Levent",
            "İstanbul|Mahmutbey",
            "İstanbul|Mahmutpaşa",
            "İstanbul|Maslak",
            "İstanbul|Mecidiyeköy",
            "İstanbul|Mehmetakif",
            "İstanbul|Mehterçeşme",
            "İstanbul|Merdivenköy",
            "İstanbul|Merkez Köyler",
            "İstanbul|Merter",
            "İstanbul|Meşrutiyet",
            "İstanbul|Mimarsinan",
            "İstanbul|Muratpaşa",
            "İstanbul|Muratreis",
            "İstanbul|Mustafakemal",
            "İstanbul|Namıkkemal",
            "İstanbul|Necipfazıl",
            "İstanbul|Numunebağ",
            "İstanbul|Okmeydanı",
            "İstanbul|Ondokuzmayıs(19 Mayıs)",
            "İstanbul|Orhanlı",
            "İstanbul|Orhantepe",
            "İstanbul|Ortaköy",
            "İstanbul|Osmanağa",
            "İstanbul|Osmangazi",
            "İstanbul|Ömerli",
            "İstanbul|Örnek",
            "İstanbul|Pangaltı",
            "İstanbul|Paşabahçe",
            "İstanbul|Pürtelaş",
            "İstanbul|Rami",
            "İstanbul|Rasimpaşa",
            "İstanbul|Rumelihisarı",
            "İstanbul|Saadetdere",
            "İstanbul|Sahrayıcedit",
            "İstanbul|Sanayi",
            "İstanbul|Sanayi",
            "İstanbul|Sarıgazi",
            "İstanbul|Sarıyer",
            "İstanbul|Sefaköy",
            "İstanbul|Selimiye",
            "İstanbul|Selimpaşa",
            "İstanbul|Seyitnizam",
            "İstanbul|Seyrantepe",
            "İstanbul|Silivri",
            "İstanbul|Sirkeci",
            "İstanbul|Siyavuşpaşa",
            "İstanbul|Soğanlı",
            "İstanbul|Soğanlık",
            "İstanbul|Suadiye",
            "İstanbul|Sultanahmet",
            "İstanbul|Sultançiftliği",
            "İstanbul|Şehremini",
            "İstanbul|Şeyhli",
            "İstanbul|Şile",
            "İstanbul|Şirinevler",
            "İstanbul|Şirintepe",
            "İstanbul|Şişli",
            "İstanbul|Tahtakale",
            "İstanbul|Taksim",
            "İstanbul|Tarabya",
            "İstanbul|Tarlabaşı",
            "İstanbul|Taşdelen",
            "İstanbul|Taşoluk",
            "İstanbul|Telsiz",
            "İstanbul|Tepecik",
            "İstanbul|Tersaneler",
            "İstanbul|Teşvikiye",
            "İstanbul|Tokatköy",
            "İstanbul|Topkapı",
            "İstanbul|Topselvi",
            "İstanbul|Tozkoparan",
            "İstanbul|Turgutreis",
            "İstanbul|Türkali",
            "İstanbul|Uğurmumcu",
            "İstanbul|Ünalan",
            "İstanbul|Vefa",
            "İstanbul|Yakacık",
            "İstanbul|Yakuplu",
            "İstanbul|Yalı",
            "İstanbul|Yavuztürk",
            "İstanbul|Yayalar",
            "İstanbul|Yenibosna",
            "İstanbul|Yeniçamlıca",
            "İstanbul|Yenidoğan",
            "İstanbul|Yeniköy",
            "İstanbul|Yenisahra",
            "İstanbul|Yenişehir",
            "İstanbul|Yeşilköy",
            "İstanbul|Yeşilpınar",
            "İstanbul|Yıldırım",
            "İstanbul|Yıldıztabya",
            "İstanbul|Yukarıdudullu",
            "İstanbul|Zeytinlik",
            "İstanbul|Zuhuratbaba",
            "İstanbul|Zübeydehanım",
            "İstanbul|Zümrütevler",
            "İzmir|Alaçatı",
            "İzmir|Alaybey",
            "İzmir|Aliağa",
            "İzmir|Alpaslan",
            "İzmir|Alsancak",
            "İzmir|Altındağ",
            "İzmir|Armutlu",
            "İzmir|Asarlık",
            "İzmir|Atatürk",
            "İzmir|Ayaskent",
            "İzmir|Ayrancılar",
            "İzmir|Bademli",
            "İzmir|Bağarası",
            "İzmir|Bağyurdu",
            "İzmir|Balatçık",
            "İzmir|Balcova",
            "İzmir|Basmane",
            "İzmir|Bayındır",
            "İzmir|Bayraklı",
            "İzmir|Belevi",
            "İzmir|Bergama",
            "İzmir|Beydağ",
            "İzmir|Birgi",
            "İzmir|Bornova",
            "İzmir|Bozdağ",
            "İzmir|Bölcek",
            "İzmir|Buca",
            "İzmir|Büyükçiğli",
            "İzmir|Canlı",
            "İzmir|Cumhuriyet",
            "İzmir|Çamdibi",
            "İzmir|Çandarlı",
            "İzmir|Çaybaşı",
            "İzmir|Çaylı",
            "İzmir|Çeşme",
            "İzmir|Çırpı",
            "İzmir|Değirmendere",
            "İzmir|Denizbostanlısı",
            "İzmir|Dikili",
            "İzmir|Doğanbey",
            "İzmir|Egekent",
            "İzmir|Emiralem",
            "İzmir|Eşrefpaşa",
            "İzmir|Evka1",
            "İzmir|Fahrettinaltay",
            "İzmir|Foça",
            "İzmir|Gaziemir",
            "İzmir|Gerenköy",
            "İzmir|Göçbeyli",
            "İzmir|Gökçen",
            "İzmir|Gölcük",
            "İzmir|Görece",
            "İzmir|Gültepe",
            "İzmir|Gümüldür",
            "İzmir|Gümüşpala",
            "İzmir|Gürçeşme",
            "İzmir|Güzelbahçe",
            "İzmir|Güzelyalı",
            "İzmir|Harmandalı",
            "İzmir|Hatay",
            "İzmir|Helvacı",
            "İzmir|Işıkkent",
            "İzmir|İmbatlı",
            "İzmir|İnciraltı",
            "İzmir|İstasyonaltı",
            "İzmir|İşçievleri",
            "İzmir|Kahramanlar",
            "İzmir|Karabağlar",
            "İzmir|Karaburun",
            "İzmir|Karşıyaka",
            "İzmir|Kayaköy",
            "İzmir|Kaymakçı",
            "İzmir|Kaynaklar",
            "İzmir|Kazımdirik"});
            this.comboBox1.Location = new System.Drawing.Point(165, 119);
            this.comboBox1.Name = "comboBox1";
            this.comboBox1.Size = new System.Drawing.Size(121, 28);
            this.comboBox1.TabIndex = 3;
            // 
            // comboBox2
            // 
            this.comboBox2.FormattingEnabled = true;
            this.comboBox2.Items.AddRange(new object[] {
            "Satılık",
            "Kiralık"});
            this.comboBox2.Location = new System.Drawing.Point(167, 454);
            this.comboBox2.Name = "comboBox2";
            this.comboBox2.Size = new System.Drawing.Size(121, 28);
            this.comboBox2.TabIndex = 4;
            // 
            // label3
            // 
            this.label3.AutoSize = true;
            this.label3.Location = new System.Drawing.Point(58, 457);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(72, 20);
            this.label3.TabIndex = 5;
            this.label3.Text = "sat/kirala";
            // 
            // label4
            // 
            this.label4.AutoSize = true;
            this.label4.Location = new System.Drawing.Point(58, 178);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(78, 20);
            this.label4.TabIndex = 6;
            this.label4.Text = "oda sayısı";
            // 
            // comboBox3
            // 
            this.comboBox3.FormattingEnabled = true;
            this.comboBox3.Items.AddRange(new object[] {
            "1+1",
            "2+1",
            "3+1",
            "4+1",
            "studio daire"});
            this.comboBox3.Location = new System.Drawing.Point(165, 178);
            this.comboBox3.Name = "comboBox3";
            this.comboBox3.Size = new System.Drawing.Size(121, 28);
            this.comboBox3.TabIndex = 7;
            // 
            // label7
            // 
            this.label7.AutoSize = true;
            this.label7.Location = new System.Drawing.Point(70, 307);
            this.label7.Name = "label7";
            this.label7.Size = new System.Drawing.Size(43, 20);
            this.label7.TabIndex = 10;
            this.label7.Text = "Fiyat";
            // 
            // label8
            // 
            this.label8.AutoSize = true;
            this.label8.Location = new System.Drawing.Point(58, 235);
            this.label8.Name = "label8";
            this.label8.Size = new System.Drawing.Size(85, 20);
            this.label8.TabIndex = 11;
            this.label8.Text = "Metrekare:";
            // 
            // textBox1
            // 
            this.textBox1.Location = new System.Drawing.Point(167, 307);
            this.textBox1.Name = "textBox1";
            this.textBox1.Size = new System.Drawing.Size(100, 26);
            this.textBox1.TabIndex = 12;
            // 
            // textBox2
            // 
            this.textBox2.Location = new System.Drawing.Point(167, 232);
            this.textBox2.Name = "textBox2";
            this.textBox2.Size = new System.Drawing.Size(100, 26);
            this.textBox2.TabIndex = 13;
            // 
            // textBox4
            // 
            this.textBox4.Location = new System.Drawing.Point(934, 286);
            this.textBox4.Name = "textBox4";
            this.textBox4.Size = new System.Drawing.Size(100, 26);
            this.textBox4.TabIndex = 15;
            // 
            // textBox6
            // 
            this.textBox6.Location = new System.Drawing.Point(934, 141);
            this.textBox6.Name = "textBox6";
            this.textBox6.Size = new System.Drawing.Size(100, 26);
            this.textBox6.TabIndex = 17;
            // 
            // label5
            // 
            this.label5.AutoSize = true;
            this.label5.Location = new System.Drawing.Point(801, 141);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(83, 20);
            this.label5.TabIndex = 18;
            this.label5.Text = "Ad-Soyad:";
            this.label5.Click += new System.EventHandler(this.label5_Click);
            // 
            // label9
            // 
            this.label9.AutoSize = true;
            this.label9.Location = new System.Drawing.Point(815, 241);
            this.label9.Name = "label9";
            this.label9.Size = new System.Drawing.Size(0, 20);
            this.label9.TabIndex = 19;
            // 
            // label10
            // 
            this.label10.AutoSize = true;
            this.label10.Location = new System.Drawing.Point(801, 289);
            this.label10.Name = "label10";
            this.label10.Size = new System.Drawing.Size(58, 20);
            this.label10.TabIndex = 20;
            this.label10.Text = "Tel No:";
            this.label10.Click += new System.EventHandler(this.label10_Click);
            // 
            // label11
            // 
            this.label11.AutoSize = true;
            this.label11.Location = new System.Drawing.Point(915, 63);
            this.label11.Name = "label11";
            this.label11.Size = new System.Drawing.Size(111, 20);
            this.label11.TabIndex = 21;
            this.label11.Text = "İletişim Bilgileri";
            // 
            // kaydet1
            // 
            this.kaydet1.Location = new System.Drawing.Point(350, 514);
            this.kaydet1.Name = "kaydet1";
            this.kaydet1.Size = new System.Drawing.Size(108, 44);
            this.kaydet1.TabIndex = 23;
            this.kaydet1.Text = "kaydet";
            this.kaydet1.UseVisualStyleBackColor = true;
            // 
            // sil
            // 
            this.sil.Location = new System.Drawing.Point(567, 508);
            this.sil.Name = "sil";
            this.sil.Size = new System.Drawing.Size(172, 50);
            this.sil.TabIndex = 24;
            this.sil.Text = "sil";
            this.sil.UseVisualStyleBackColor = true;
            // 
            // grnt
            // 
            this.grnt.Location = new System.Drawing.Point(142, 519);
            this.grnt.Name = "grnt";
            this.grnt.Size = new System.Drawing.Size(123, 39);
            this.grnt.TabIndex = 25;
            this.grnt.Text = "Görüntüle";
            this.grnt.UseVisualStyleBackColor = true;
            this.grnt.Click += new System.EventHandler(this.grnt_Click);
            // 
            // düzelt
            // 
            this.düzelt.Location = new System.Drawing.Point(836, 508);
            this.düzelt.Name = "düzelt";
            this.düzelt.Size = new System.Drawing.Size(107, 50);
            this.düzelt.TabIndex = 26;
            this.düzelt.Text = "Düzelt";
            this.düzelt.UseVisualStyleBackColor = true;
            // 
            // listView1
            // 
            this.listView1.Columns.AddRange(new System.Windows.Forms.ColumnHeader[] {
            this.columnHeader9,
            this.columnHeader10,
            this.columnHeader11,
            this.columnHeader12,
            this.columnHeader13,
            this.columnHeader14,
            this.columnHeader15,
            this.columnHeader16,
            this.columnHeader17,
            this.columnHeader1});
            this.listView1.HideSelection = false;
            this.listView1.Location = new System.Drawing.Point(150, 578);
            this.listView1.Name = "listView1";
            this.listView1.Size = new System.Drawing.Size(935, 273);
            this.listView1.TabIndex = 27;
            this.listView1.UseCompatibleStateImageBehavior = false;
            this.listView1.View = System.Windows.Forms.View.Details;
            this.listView1.SelectedIndexChanged += new System.EventHandler(this.listView1_SelectedIndexChanged);
            // 
            // columnHeader9
            // 
            this.columnHeader9.Text = "EmlakGazi";
            this.columnHeader9.Width = 90;
            // 
            // columnHeader10
            // 
            this.columnHeader10.Text = "SıraNo";
            // 
            // columnHeader11
            // 
            this.columnHeader11.Text = "Şehir/Semt";
            this.columnHeader11.Width = 100;
            // 
            // columnHeader12
            // 
            this.columnHeader12.Text = "Oda";
            // 
            // columnHeader13
            // 
            this.columnHeader13.Text = "Metrekare";
            this.columnHeader13.Width = 90;
            // 
            // columnHeader14
            // 
            this.columnHeader14.Text = "Fiyat";
            // 
            // columnHeader15
            // 
            this.columnHeader15.Text = "Ad/Soyad";
            this.columnHeader15.Width = 100;
            // 
            // columnHeader16
            // 
            this.columnHeader16.Text = "Telefon";
            this.columnHeader16.Width = 90;
            // 
            // columnHeader17
            // 
            this.columnHeader17.Text = "Notlar";
            this.columnHeader17.Width = 70;
            // 
            // columnHeader1
            // 
            this.columnHeader1.Text = "Satılık/Kiralık";
            this.columnHeader1.Width = 100;
            // 
            // textBox7
            // 
            this.textBox7.Location = new System.Drawing.Point(165, 78);
            this.textBox7.Name = "textBox7";
            this.textBox7.Size = new System.Drawing.Size(100, 26);
            this.textBox7.TabIndex = 29;
            // 
            // textBox5
            // 
            this.textBox5.Location = new System.Drawing.Point(167, 377);
            this.textBox5.Name = "textBox5";
            this.textBox5.Size = new System.Drawing.Size(100, 26);
            this.textBox5.TabIndex = 30;
            this.textBox5.TextChanged += new System.EventHandler(this.textBox5_TextChanged);
            // 
            // label12
            // 
            this.label12.AutoSize = true;
            this.label12.Location = new System.Drawing.Point(62, 380);
            this.label12.Name = "label12";
            this.label12.Size = new System.Drawing.Size(51, 20);
            this.label12.TabIndex = 31;
            this.label12.Text = "Notlar";
            // 
            // label6
            // 
            this.label6.AutoSize = true;
            this.label6.Location = new System.Drawing.Point(70, 81);
            this.label6.Name = "label6";
            this.label6.Size = new System.Drawing.Size(65, 20);
            this.label6.TabIndex = 32;
            this.label6.Text = "Sıra No:";
            // 
            // Form2
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(9F, 20F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1344, 863);
            this.Controls.Add(this.label6);
            this.Controls.Add(this.label12);
            this.Controls.Add(this.textBox5);
            this.Controls.Add(this.textBox7);
            this.Controls.Add(this.listView1);
            this.Controls.Add(this.düzelt);
            this.Controls.Add(this.grnt);
            this.Controls.Add(this.sil);
            this.Controls.Add(this.kaydet1);
            this.Controls.Add(this.label11);
            this.Controls.Add(this.label10);
            this.Controls.Add(this.label9);
            this.Controls.Add(this.label5);
            this.Controls.Add(this.textBox6);
            this.Controls.Add(this.textBox4);
            this.Controls.Add(this.textBox2);
            this.Controls.Add(this.textBox1);
            this.Controls.Add(this.label8);
            this.Controls.Add(this.label7);
            this.Controls.Add(this.comboBox3);
            this.Controls.Add(this.label4);
            this.Controls.Add(this.label3);
            this.Controls.Add(this.comboBox2);
            this.Controls.Add(this.comboBox1);
            this.Controls.Add(this.label2);
            this.Controls.Add(this.label1);
            this.Name = "Form2";
            this.Text = "şehir";
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.ComboBox comboBox1;
        private System.Windows.Forms.ComboBox comboBox2;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.ComboBox comboBox3;
        private System.Windows.Forms.Label label7;
        private System.Windows.Forms.Label label8;
        private System.Windows.Forms.TextBox textBox1;
        private System.Windows.Forms.TextBox textBox2;
        private System.Windows.Forms.TextBox textBox4;
        private System.Windows.Forms.TextBox textBox6;
        private System.Windows.Forms.Label label5;
        private System.Windows.Forms.Label label9;
        private System.Windows.Forms.Label label10;
        private System.Windows.Forms.Label label11;
        private System.Windows.Forms.Button sil;
        private System.Windows.Forms.Button grnt;
        private System.Windows.Forms.Button düzelt;
        private System.Windows.Forms.ListView listView1;
        private System.Windows.Forms.TextBox textBox7;
        private System.Windows.Forms.TextBox textBox5;
        private System.Windows.Forms.Label label12;
        private System.Windows.Forms.ColumnHeader columnHeader9;
        private System.Windows.Forms.ColumnHeader columnHeader10;
        private System.Windows.Forms.ColumnHeader columnHeader11;
        private System.Windows.Forms.ColumnHeader columnHeader12;
        private System.Windows.Forms.ColumnHeader columnHeader13;
        private System.Windows.Forms.ColumnHeader columnHeader14;
        private System.Windows.Forms.ColumnHeader columnHeader15;
        private System.Windows.Forms.ColumnHeader columnHeader16;
        private System.Windows.Forms.ColumnHeader columnHeader17;
        private System.Windows.Forms.ColumnHeader columnHeader1;
        private System.Windows.Forms.Button kaydet1;
        private System.Windows.Forms.Label label6;
    }
}